### ISSUE TITLE
Package not found: resolving package Immutable.re

### ISSUE THREAD

**Issue by wyze** [reasonml/reductive#4]
Full error:

```
Package not found: resolving package Immutable.re in /
Fatal error: exception BuckleScript package Immutable.re not found or built , if it is not b
uilt
Please run 'bsb -make-world', otherwise please install it
Error happened when running command /Users/neil/Projects/personal/reason-calculator/node_mod
ules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

I think since Immutable.re is listed in `bs-dependencies` that it needs to be under `dependencies` in the `package.json` as well, otherwise it won't get installed when adding `reductive` as a dependency to a project.

**Comment by rickyvetter** [comment]
Hmm - looking into how to mark bs-dependencies as dev. Immutable.re should only re required for contributions/testing.

**Comment by wyze** [comment]
Looks like this was fixed on master: https://github.com/bloomberg/bucklescript/issues/1490
